### ISSUE TITLE
MapVisitor's missing_field doesn't handle Option properly

### ISSUE THREAD

**Issue by sfackler** [arcnmx/serde-value#2]
MapVisitor's [missing_field implementation](https://github.com/arcnmx/serde-value/blob/master/src/lib.rs#L418) currently delegates to deserializing from a `Value::Unit`, but this unfortunately doesn't work for the use case of having an `Optional<Foo>` field that will be set to `None` if the field isn't provided, since `Optional`'s `Visitor` only handles `visit_some` and `visit_none`.

missing_field's default implementation gets around this by using a `ValueDeserializer` for `()`, which pays attention to the `visit_option` hint: https://github.com/serde-rs/serde/blob/master/serde/src/de/value.rs#L109-L119.

serde_json does something similar but with a local Deserializer: https://serde-rs.github.io/json/src/serde_json/value.rs.html#951 for some reason.

**Comment by sfackler** [comment]
Ah, the right fix may actually be for `Deserializer` to override the default `visit_option` implementation to map `Value::Unit` to `visit_none`: https://serde-rs.github.io/json/src/serde_json/value.rs.html#744

**Comment by arcnmx** [comment]
Hm, should `missing_field` not just return the error as the default implementation in `de::MapVisitor` does? Isn't it the `Deserialize` implementation's responsibility to react to it accordingly and replace it with a valid value if appropriate (like if you were to use `#[serde(default)]`)?

**Comment by sfackler** [comment]
I think the idea's that `#[serde(default)]` is essentially implied for the case of `Option`, but I'm not totally sure where the responsibility for that should lie. ping @erickt?

**Comment by arcnmx** [comment]
That seems like a sort of legacy feature from before `serde(default)` was a thing..? I'd lean toward explicitness especially as `Value` is meant to be a sort of lossless tokenized version of a serialization tree, but yeah, some input from @erickt would be helpful.

**Comment by erickt** [comment]
I'm trying to remember how this came about :) You're right that `#[serde(default)]` came before all this was organized. serde currently provides hooks for both the `Deserializer` and the `Deserialize` to do something special if a value is not present. For the `Deserializer`, many users of JSON may not necessarily encode `null` values since this is the behavior of JavaScript. So to be semantically correct, `serde_json` uses the `Deserializer::missing_field` hook to implement this pattern. On the `Deserialize` side, they've got `#[serde(default)]` (which might grow into supporting arbitrary expressions through https://github.com/serde-rs/serde/issues/216).

So in the case of `serde-value`, there are two things going on. First, it seems pretty reasonable to me that we should be able to deserialize an `Option<T>` from a `()`, especially since we do the same already for sequences and maps. I filed https://github.com/serde-rs/serde/issues/217 to implement it. Second, is more philosophical. By implementing `missing_field`, you're saying that your format is a bit more liberal in what it deserializes. That's perfectly fine, but it just might mean your users may get a less helpful error message saying essentially "cannot deserialize some field from a null" instead of "the field wasn't present".

I waver between having better error messages and being less of a pain in the ass to the users :) Today I'm leaning towards the latter.

Either way, it seems like if we implement `visit_unit` on the `OptionVisitor`, you and everyone else, might not need to jump through all these hoops, so I'll see if I can do that.

Does that help?

**Comment by sfackler** [comment]
Hmm, so after some more thought, I'm not sure what the right approach is here. The changes I mentioned earlier aren't sufficient because in the case where the value *is* present, it'll be an e.g. `String` which will fail to deserialize to an `Option<String>` since `visit_option` isn't overridden. It's not totally clear what should happen then, since the Value type itself has an `Option` variant.

My use case is that I want to deserialize a chunk of TOML or YAML or whatever into some value, which can then later be deserialized into some more concrete type like a struct. In Java, you'd use `JsonNode`, for example (Jackson was originally written to do JSON serialization but has since added support for other formats). It might make more sense to make my own `Value` type that's an enum composed of `serde_json::Value`, etc to make sure all of the format-specific handling gets propagated properly.

**Comment by arcnmx** [comment]
While I think missing_field should be changed back to a hard error, I'd
consider Option<X> not deserializing from X to be a bug - your use case is
essentially what this library exists for and the current behaviour is just
too inconvenient.

**Comment by sfackler** [comment]
Ah, fantastic. I think what needs to happen then is `Deserialize::visit_option` to be overridden.

**Comment by erickt** [comment]
Ah, I remember now why I didn't implement `visit_unit` for `OptionVisitor`. The question is how do we deal with formats that have first class support for Options, and those that treat optional values as being either `null`, or some value. If we have first class support, then we can represent the value `Some(())`, but if we don't, we'll always deserialize a `unit` into `None`, since there's no way to distinguish between the two cases.

I erred on being more conservative to give us the ability to represent more types, and also give more sensible errors if there's a parse issue. So I made `OptionVisitor` just handle `visit_none` and `visit_some`, and leave it up to the `Deserializer` to decide whether or not to handle options specially (and lose the ability to represent some values). Do you think it's worth it?

I'll write up this design consideration in the readme so I can point to it in the future.

Also, if you do want to support your deserializer to be able to deserialize a `String` into a `Option<String>`, you can see how I do that in [TokenDeserializer's visit_option](https://github.com/serde-rs/serde/blob/master/serde_tests/tests/token.rs#L433-L454) method. It looks ahead to the next token to see if it's either a `unit`, an `option`, or some other value.

**Comment by erickt** [comment]
You can find my writeup [here](https://github.com/serde-rs/serde#design-considerations-and-tradeoffs-for-serializers-and-deserializers).

**Comment by arcnmx** [comment]
@sfackler I've committed 5c9dced18f8a538c9bcf3150369bdcabaebfb3d8, want to give it a try and see if it works for your use case? I'm iffy on whether `Unit` should automatically coerce into `None`, I may remove that... `Deserializer` could probably use a "strict mode" or something and default it to off and then these changes would feel a bit better and less automagical.

**Comment by arcnmx** [comment]
@erickt thanks! I think it would make sense for this library to support both modes, considering it may be used in different ways. It's nice to have a strict value tree, and it's also nice to have an "interim" value type that can be used to defer deserialization for later (for example if the type isn't known at deserialization time, or it relies on other contextual information in the data, etc). The thing is that you lose information about how strict the deserialization should be when you defer it like that, since you're no longer using same the deserializer.
